<?php
  $listOrdered = $this->listEntity->getOrdered();
  $pageTitle = $listOrdered
    ? $this->translate('ReservationList::form_response')
    : $this->translate('ReservationList::Add to reservation list');
  $toList = $listOrdered
    ? $this->translate('ReservationList::View hold request')
    : $this->translate('ReservationList::Continue to sending the hold request');

  $user = $this->auth()->getUserObject();
  $contextDriver = $this->driver ?? null;
  // Set up breadcrumbs:
  if ($contextDriver) {
    $this->breadcrumbs()->set(...$this->recordLinker()->getBreadcrumbParams($this->driver))
      ->add($pageTitle, active: true);
  }
?>

<?=$this->component('page-title', ['title' => $pageTitle]);?>

<?php if (!$this->listEntity->getOrdered() && $contextDriver): ?>
  <p><?=$this->transEsc('ReservationList::resource_added_to_list', ['%%resource%%' => $this->driver->getTitle(), '%%list%%' => $this->listEntity->getTitle($this->layout()->userLang)]);?></p>
<?php endif; ?>
<?php if ($this->listEntity->getOrdered()): ?>
  <p><?=$this->transEsc('ReservationList::after_order_instructions');?></p>
<?php endif; ?>

<div class="btn-group">
  <a class="btn btn-primary" href="<?=$this->url('reservationlist-displaylist', ['listId' => $this->listEntity->getId()])?>" data-lightbox-ignore><?=$this->escapeHtml($toList)?></a>
</div>
<div class="btn-group">
  <button class="btn btn-primary lightbox-only" data-bs-dismiss="modal"><?=$this->transEsc('close') ?></button>
</div>
