<h2><?=$this->transEsc('delete_account_title') ?></h2>
<?=$this->flashmessages();?>
<?php if ($this->accountDeleted): ?>
  <div id="delete-account-success">
    <p><?=$this->translate('delete_account_success_message'); ?></p>
    <?php
      // Logout redirect with inline script to make it lightbox compatible
      $script = "setTimeout(function() { window.location = '{$this->redirectUrl}'; }, 5000);";
    ?>
    <?=$this->assetManager()->outputInlineScriptString($script); ?>
  </div>
<?php else: ?>
  <div class="delete-account-confirm">
    <?=$this->partial('myresearch/logged-in-as.phtml', ['user' => $user]);?>
    <form id="delete-account" method="post" action="<?=$this->url('myresearch-deleteaccount') ?>" name="deleteAccount">
      <h3><?=$this->transEsc('delete_account_confirm'); ?></h3>
      <p><?=$this->translate('delete_account_description_html'); ?></p>
      <input type="hidden" name="csrf" value="<?=$this->escapeHtmlAttr($this->auth()->getManager()->getCsrfHash())?>">
      <input id="delete-account-submit" class="btn btn-danger" type="submit" name="submitButton" value="<?=$this->transEscAttr('delete_account_title'); ?>">
      <input id="delete-account-cancel" class="btn btn-primary" type="submit" name="reset" data-bs-dismiss="modal" value="<?=$this->transEscAttr('confirm_dialog_cancel'); ?>">
    </form>
  </div>
<?php endif; ?>
