<!-- START of: finna - content/help-comments-ratings_en-gb.phtml -->
<?php $this->headTitle($this->translate('tabs_help-comments-ratings'))?>

<?php if ($this->resolver('content/help-tabs.phtml')): ?>
  <?=$this->render('content/help-tabs.phtml', ['activeTab' => 'help-comments-ratings'])?>
<?php endif; ?>
<div class="sidebar left">
  <div class="content-navigation-menu">
  </div>
</div>
<div class="mainbody right">
  <div id="commentsratings" class="content-section">
    <h2>Comments and Ratings</h2>
    <p>You can comment on all the material found in Finna. In addition, you may add a rating of one to five stars on certain types of material, such as books.</p>
    <p>You need a Finna account for commenting and reviewing. Instructions for creating a Finna account can be found on the help page <a href="https://finna.fi/Content/help-account?lng=en-gb">Login and your account</a>.</p>
    <p>Organisations will monitor comments on the material they respectively manage and are obligated to moderate them when necessary. This means that organisations can hide inappropriate or unnecessary comments. You can also report inappropriate comments yourself on the Comments tab of the material.</p>
    <p>Moderators comply with moderating principles when deciding to hide a comment. In particular, comments reported by other users will be checked separately. If necessary, please contact the organisation providing the material.  Organisations’ rationale for moderating comments is available in the Finna Guidelines for Commenting.</p>
    <p>You can view your comments and ratings in the ‘Comments and Ratings’ sections of the ‘Your Account’ menu. There, you will also see any comments of yours that may have been hidden by moderators.  There is also a link to the record page where you can edit or delete your comment. </p>
    <p>Please use the comment section only for commenting on the material. Send any questions and comments on the material to its responsible organisation by using the ‘Contact us’ button. Feedback on Finna's features can be sent using the ‘Feedback’ form.</p>
  </div>
  <div id="commentguidelines" class="content-section">
    <h2>Finna Guidelines for Commenting</h2>
    <p>Observe good manners and the law, while respecting other users. The following types of comments will be hidden:</p>
    <ul class="list-bullets">
      <li>Unlawful comments</li>
      <li>Offensive comments</li>
      <li>Irrelevant or inappropriate comments</li>
    </ul>
    <p>Advertising or adding links is not permitted in Finna. The following types of comments will be hidden:</p>
    <ul class="list-bullets">
      <li>Comments containing links. Comments should not include links to external websites due to information security risks.</li>
      <li>Comments aimed at directing readers, for example, to the commenter’s own blog or other service for commercial purposes. Advertising in Finna is not permitted. </li>
    </ul>
    <p>
      Even if you disagree on the statements made in the work with the author, you must not make personal attacks in the comments. You have the right to be sceptical or critical but your comments should remain respectful. You may come across someone you recognise in image material published in Finna.  If the person in question is alive and not a public figure, you may not publish their personal information in a public service. You may send information related to the person in question to the organisation providing the material by using the ‘Contact us’ button.
    </p>
    <p>Comments violating the following principles are hidden:</p>
    <ul class="list-bullets">
      <li>Comments containing <a href="https://commission.europa.eu/law/law-topic/data-protection/rules-business-and-organisations/legal-grounds-processing-data/sensitive-data/what-personal-data-considered-sensitive_en" target="_blank">sensitive personal information</a> or information pertaining to anyone’s personal life. The privacy of others is protected.</li>
      <li>Comments naming a potentially living person, unless said person is already named in the material itself or is a well-known public figure.</li>
      <li>Offensive comments pertaining to the gender, age, origin, language, religion or other personal characteristics of the author or persons otherwise present in the material. Comments should be relevant to the material.</li>
    </ul>

    <p>The following principles will also be adhered to ensure that the comment section will serve its purpose.</p>
    <ul class="list-bullets">
      <li>Plot disclosures of fictional material, such as books or films, should be excluded from comments.</li>
      <li>Questions to the material provider and usability issues should be primarily submitted through the relevant forms.</li>
    </ul>
    <p>If necessary, you can also edit or delete a comment you have made.</p>
    <p>Your comment will be published under your name or alias in all Finna search services and online libraries where the material is displayed. All comments are public. You can choose an alias and change it in the <a href="<?=$this->url('myresearch-profile')?>">Profile</a> section of your account.</p>
  </div>
</div>
<!-- END of: finna - content/help-comments-ratings_en-gb.phtml -->
