<!-- START of: finna - content/help-comments-ratings_se.phtml -->
<?php $this->headTitle($this->translate('tabs_help-comments-ratings'))?>

<?php if ($this->resolver('content/help-tabs.phtml')): ?>
  <?=$this->render('content/help-tabs.phtml', ['activeTab' => 'help-comments-ratings'])?>
<?php endif; ?>
<div class="sidebar left">
  <div class="content-navigation-menu">
  </div>
</div>
<div class="mainbody right">
  <div id="commentsratings" class="content-section">
    <h2>Kommeanttat ja árvvoštallamat</h2>
    <p>Finnas sáhtát kommenteret buot materiála, mii lea gávdnomis. Dan lassin muhtin materiálaide, ovdamearkka dihte girjjiide, sáhtát lasihit árvvoštallama.</p>
    <p>Kommenteremii dárbbašat Finna-konttu. Rávvagiid Finna-konttu ráhkadeapmái gávnnat <a href="https://finna.fi/Content/help-account?lng=se">Čálihuvvan ja iežas kontu</a> rávvagis.</p>
    <p>Materiálaid hálddašeaddji organisašuvnnat čuvvot iežaset materiálaide laktáseaddji kommeanttaid ja leat geatnegahtton dárbbu mielde modereret daid. Dát dárkkuha, ahte organisašuvnnat sáhttet čiehkat heivemeahttun dahje dárbbašmeahttun kommeanttaid. Sáhtát maiddái ieš almmuhit heivemeahttun kommeanttaid materiála Kommeanttat-gaskasiiddus.</p>
    <p>Modererejeaddji čuovvu modererenprinsihpaid, go son mearrida kommeantta čiehkamis. Erenomážit eará geavaheaddjiid almmuhan kommeanttat šaddet sierradárkkodeapmái. Váldde dárbbu mielde oktavuođa materiála fáladeaddji organisašuvdnii.</p>
    <p>Oainnát iežat kommeanttaid ja árvvoštallamiid Iežas kontu -fálu Kommeanttat ja árvvoštallamat -oasis. Oainnát doppe maiddái vejolaččat modererejeaddji čiehkan kommeanttaid.</p>
    <p>Använd kommentarsdelen endast för att kommentera material. Skicka frågor och kommentarer om material till den organisation som tillhandahåller materialet genom knappen Kontaktformulär. Respons på Finnas funktioner kan skickas via blanketten Respons.</p>
  </div>
  <div id="commentguidelines" class="content-section">
    <h2>Finna kommenterenprinsihpat</h2>
    <p>Čuovo buriid dábiid ja lága, ja gudnejahte eará geavaheaddjiid. Čuovvovaš kommeanttat čihkkojuvvojit:</p>
    <ul class="list-bullets">
      <li>Lágavuostásaš kommeanttat</li>
      <li>Heivemeahttun kommeanttat</li>
      <li>Áššái laktáskeahtes dahje buori dábi vuostásaš kommeanttat</li>
    </ul>
    <p>Finnas máinnusteapmi dahje liŋkkaid lasiheapmi ii leat lobálaš. Čuovvovaš kommeanttat čihkkojuvvojit:</p>
    <ul class="list-bullets">
      <li>Liŋkkaid sisdoalli kommeanttat. Kommeanttain eai galggašedje leat liŋkkat olggobealat siidduide diehtodorvoriskka dihte.</li>
      <li>Kommeanttat, maid ulbmilin lea gávppálaččat láidet geavaheaddji ovdamearkka dihte kommenterejeaddji iežas bloggii dahje eará bálvalussii. Máinnusteapmi Finnas ii leat lobálaš.</li>
    </ul>
    <p>
      Vaikko livččii sierra oaivilis duoji dahkkiiguin, ii galgga fallehit kommeanttain olbmo vuostá. Oažžu leat eahpideaddji dahje kritihkalaš, muhto kommeanttat galggašedje bissut áššálažžan, eaige mannat persovnnalaš áššiide. Finnas almmustahtton govvamateriálas sáhttá dovdat oahpes olbmuid. Jus jearaldagas lea vejolaččat ealli olmmoš, gii ii leat almmusvuođas, dán olbmo dieđuid ii oaččo almmustahttit almmolaš bálvalusas.
    </p>
    <p>Čuovvovaš prinsihpaid vuostásaš kommeanttat čihkkojuvvojit:</p>
    <ul class="list-bullets">
      <li>Kommentarer som innehåller <a href="https://commission.europa.eu/law/law-topic/data-protection/rules-business-and-organisations/legal-grounds-processing-data/sensitive-data/what-personal-data-considered-sensitive_en" target="_blank">Árgalunddolaš heaggadieđuid</a> dahje geange priváhtaeallimii gullevaš áššiid sisdoalli kommeanttat. Suodjalit earáid priváhtavuođa.</li>
      <li>Vejolaččat ealli, ovttaskas olbmo namaheapmi ii leat lobálaš jus dat ii boađe ovdan juo materiála oktavuođas dahje jearaldagas ii leat dovddus almmolašvuođa olmmoš.</li>
      <li>Dahkki dahje materiála eará olbmuid sohkabeallái, ahkái, sohkaduogážii, gillii, oskkoldahkii dahje eará persovnnalaš iešvuhtii laktáseaddji loavkideaddji kommeanttat. Kommeantta sisdoallu galggašii laktásit materiálii.</li>
    </ul>

    <p>Doallat dan lassin gitta čuovvovaš prinsihpain, vai kommeanttagieddi bálvalivččii nu bures go vejolaš.</p>
    <ul class="list-bullets">
      <li>Fiktiivvalaš materiála, nugo girjjiid ja ealligovaid jutnii laktáseaddji kommeanttaid galggašii guođđit eret kommeanttain.</li>
      <li>Jearaldagat materiála fáladeaddjái ja geavahanváttisvuođat sáddejuvvojit váldoáššis daidda dárkkuhuvvon skoviiguin.</li>
    </ul>
    <p>Sáhtát maiddái dárbbu mielde hábmet dahje sihkkut iežat kommeanttaid.</p>
    <p>Du kommeanttat almmustahttojuvvojit du namain dahje nammamearkkain buot Finna-ohcanbálvalusain ja -neahttagirjerájuin, main materiála lea oidnosis. Buot kommeanttat leat almmolaččat. Sáhtát váldit nammamearkka geavahussii ja molsut dan <a href="<?=$this->url('myresearch-profile')?>">Iežas dieđuin</a> iežat konttus.</p>
  </div>
</div>
<!-- END of: finna - content/help-comments-ratings_se.phtml -->
