<!-- START of: finna - content/help-comments-ratings_fi.phtml -->
<?php $this->headTitle($this->translate('tabs_help-comments-ratings'))?>

<?php if ($this->resolver('content/help-tabs.phtml')): ?>
  <?=$this->render('content/help-tabs.phtml', ['activeTab' => 'help-comments-ratings'])?>
<?php endif; ?>
<div class="sidebar left">
  <div class="content-navigation-menu">
  </div>
</div>
<div class="mainbody right">
  <div id="commentsratings" class="content-section">
    <h2>Kommentit ja arviot</h2>
    <p>Finnassa voit kommentoida kaikkia sieltä löytyviä aineistoja. Lisäksi joihinkin aineistoihin, kuten kirjoihin, voit lisätä arvion eli 1-5 tähteä.</p>
    <p>Kommentoimiseen ja arvioimiseen tarvitset Finna-tilin. Ohjeet Finna-tilin luomiseen löydät <a href="https://finna.fi/Content/help-account">Kirjautuminen ja oma tili</a> -ohjeesta.</p>
    <p>Aineistoja hallinnoivat organisaatiot seuraavat omiin aineistoihinsa liittyviä kommentteja ja ovat velvoitettuja tarvittaessa moderoimaan niitä. Tämä tarkoittaa, että organisaatiot voivat piilottaa sopimattomia tai tarpeettomia kommentteja. Voit myös itse ilmiantaa sopimattomia kommentteja aineiston Kommentit-välilehdellä.</p>
    <p>Moderoija noudattaa moderointiperiaatteita, kun hän päättää kommentin piilottamisesta. Erityisesti muiden käyttäjien ilmiantamat kommentit tarkistetaan erikseen. Ota tarvittaessa yhteyttä aineiston tarjoavaan organisaatioon. Organisaatioiden perustelut kommentoinnin moderointiin löydät Finnan kommentointiperiaatteet -ohjeesta.</p>
    <p>Näet omat kommenttisi ja arviosi Oma tili -valikon Kommentit ja arviot -osioista. Näet sieltä myös mahdollisesti moderoijan piilottamat kommenttisi. Kommenteistasi löydät linkin tietuesivuun, josta pääset muokkaamaan tai poistamaan kommenttisi.</p>
  </div>
  <div id="commentguidelines" class="content-section">
    <h2>Finnan kommentointiperiaatteet</h2>
    <p>Noudata hyviä tapoja ja lakia, sekä kunnioita muita käyttäjiä. Seuraavanlaiset kommentit piilotetaan:</p>
    <ul class="list-bullets">
      <li>Lainvastaiset kommentit</li>
      <li>Alatyyliset kommentit</li>
      <li>Asiaan liittymättömät tai hyvän tavan vastaiset kommentit</li>
    </ul>
    <p>Finnassa mainostaminen tai linkkien lisääminen ei ole sallittua. Seuraavanlaiset kommentit piilotetaan:</p>
    <ul class="list-bullets">
      <li>Linkkejä sisältävät kommentit. Kommenteissa ei tulisi olla linkkejä ulkopuolisille sivustoille tietoturvariskien vuoksi.</li>
      <li>Kommentit, jotka pyrkivät kaupallisessa mielessä ohjaamaan esimerkiksi kommentoijan omaan blogiin tai muuhun palveluun. Mainostaminen Finnassa ei ole luvallista.</li>
    </ul>
    <p>
      Vaikka olisi eri mieltä teoksessa esitetyistä väitteistä tekijän kanssa, ei hyökätä kommenteissa henkilöä vastaan. Saa olla epäileväinen tai kriittinen, mutta kommenttien tulisi pysyä asiallisina, eikä mennä henkilökohtaisuuksiin. Finnassa julkaistusta kuva-aineistosta voi tunnistaa tuttuja henkilöitä. Jos kyseessä on mahdollisesti elossa oleva henkilö, joka ei ole julkisuudessa, tämän henkilön tietoja ei saa julkisessa palvelussa julkaista. Henkilön tiedot voi lähettää aineiston tarjoavalle organisaatiolle tietuesivulta “Ota yhteyttä” -painikkeen kautta.
    </p>
    <p>Seuraavia periaatteita rikkovat kommentit piilotetaan:</p>
    <ul class="list-bullets">
      <li><a href="https://commission.europa.eu/law/law-topic/data-protection/rules-business-and-organisations/legal-grounds-processing-data/sensitive-data/what-personal-data-considered-sensitive_fi" target="_blank">Arkaluonteisia henkilötietoja</a> tai kenenkään yksityiselämään kuuluvia asioita sisältävät kommentit. Suojataan muiden yksityisyyttä.</li>
      <li>Mahdollisesti elossa olevan, yksittäisen henkilön nimeäminen ei ole sallittua, ellei se tule ilmi jo aineistosta itsestään tai kyseessä ole tunnettu julkisuuden henkilö.</li>
      <li>Tekijän tai aineistossa muuten esiintyvien henkilöiden sukupuoleen, ikään, syntyperään, kieleen, uskontoon tai muuhun henkilökohtaiseen ominaisuuteen liittyvät loukkaavat kommentit. Kommentin sisällön tulisi liittyä aineistoon.</li>
    </ul>

    <p>Pidetään lisäksi kiinni seuraavista periaatteista, jotta kommenttiosio olisi käyttötarkoituksensa mukainen.</p>
    <ul class="list-bullets">
      <li>Fiktiivisen aineiston, kuten kirjojen ja elokuvien juonipaljastukset tulisi jättää pois kommenteista.</li>
      <li>Kysymykset aineiston tarjoajalle ja käytettävyysongelmat laitetaan ensisijaisesti niille tarkoitettujen lomakkeiden kautta.</li>
    </ul>
    <p>Voit myös tarvittaessa muokata tai poistaa tekemäsi kommentin.</p>
    <p>Kommenttisi julkaistaan nimelläsi tai nimimerkilläsi kaikissa Finna-hakupalveluissa ja -verkkokirjastoissa, joissa aineisto on näkyvillä. Kaikki kommentit ovat julkisia. Voit ottaa nimimerkin käyttöön ja vaihtaa sen <a href="<?=$this->url('myresearch-profile')?>">Omat tiedot</a> -sivulta.</p></p>
  </div>
</div>
<!-- END of: finna - content/help-comments-ratings_fi.phtml -->
