<!-- START of: finna - content/help-comments-ratings_sv.phtml -->
<?php $this->headTitle($this->translate('tabs_help-comments-ratings'))?>

<?php if ($this->resolver('content/help-tabs.phtml')): ?>
  <?=$this->render('content/help-tabs.phtml', ['activeTab' => 'help-comments-ratings'])?>
<?php endif; ?>
<div class="sidebar left">
  <div class="content-navigation-menu">
  </div>
</div>
<div class="mainbody right">
  <div id="commentsratings" class="content-section">
    <h2>Kommentarer och betyg</h2>
    <p>På Finna kan du kommentera allt material som finns där. En del material, såsom böcker, kan du ge en bedömning, det vill säga 1–5 stjärnor.</p>
    <p>För att kunna skriva kommentarer och göra bedömningar behöver du ett Finna-konto. Instruktioner för att skapa ett Finna-konto hittar du på hjälpsidan <a href="https://finna.fi/Content/help-account?lng=sv">Inloggning och konto</a>.</p>
    <p>De organisationer som administrerar materialen följer kommentarerna till sina egna material och är skyldiga att vid behov moderera dem. Detta betyder att organisationer kan dölja olämpliga eller onödiga kommentarer. Du kan också själv ange olämpliga kommentarer till ett material på fliken Kommentarer.</p>
    <p>Moderatorn följer principerna för moderering när hen beslutar om huruvida en kommentar ska döljas. Särskilt kommentarer som angetts av andra användare kontrolleras separat. Ta vid behov kontakt med den organisation som tillhandahåller materialet.  Organisationernas motiveringar för att moderera kommentarer hittar du i anvisningen Finnas principer för kommentarer.</p>
    <p>Du ser dina kommentarer och bedömningar under delen Kommentarer och betyg menyn Mitt konto. Där kan du också se dina egna kommentarer som eventuellt döljs av moderatorn. Under dina kommentarer hittar du också en länk till sidan för respektive post, där du kan redigera eller radera din kommentar. </p>
    <p>Använd kommentarsdelen endast för att kommentera material. Skicka frågor och kommentarer om material till den organisation som tillhandahåller materialet genom knappen Kontaktformulär. Respons på Finnas funktioner kan skickas via blanketten Respons.</p>
  </div>
  <div id="commentguidelines" class="content-section">
    <h2>Finnas principer för kommentarer</h2>
    <p>Iaktta god sed och lagen samt respektera andra användare. Exempel på kommentarer som döljs är</p>
    <ul class="list-bullets">
      <li>Kommentarer som strider mot lagen</li>
      <li>Kommentarer på vulgärspråk</li>
      <li>Kommentarer som inte har med saken att göra eller som strider mot god sed</li>
    </ul>
    <p>Det är inte tillåtet att göra reklam eller lägga till länkar på Finna. Exempel på kommentarer som döljs är</p>
    <ul class="list-bullets">
      <li>Kommentarer som innehåller länkar. Kommentarerna ska inte innehålla länkar till externa webbplatser på grund av datasäkerhetsrisker.</li>
      <li>Kommentarer som i kommersiellt avseende strävar efter att styra användaren till exempel till kommenterarens blogg eller någon annan tjänst. Det är inte tillåtet att göra reklam på Finna.</li>
    </ul>
    <p>
      Även om man är oense om påståendena i ett verk, finns det inte skäl att gå till angrepp mot en annan person i sina kommentarer. Det är tillåtet att vara skeptisk eller kritisk men kommentarerna ska vara sakliga och inte gå till personangrepp. Du kan identifiera bekanta personer i det bildmaterial som publicerats på Finna. Om det är fråga om en person som eventuellt lever och som inte är en offentlig person, får uppgifterna om personen inte publiceras i en offentlig tjänst. Personens uppgifter kan skickas till den organisation som tillhandahåller materialet genom knappen Kontaktformulär på sidan för respektive post.
    </p>
    <p>Kommentarer som bryter mot följande principer döljs:</p>
    <ul class="list-bullets">
      <li>Kommentarer som innehåller <a href="https://commission.europa.eu/law/law-topic/data-protection/rules-business-and-organisations/legal-grounds-processing-data/sensitive-data/what-personal-data-considered-sensitive_sv" target="_blank">känsliga personuppgifter</a> eller information som tillhör en annan persons privatliv. Vi skyddar andras integritet.</li>
      <li>Det är inte tillåtet att namnge en person som eventuellt lever om det inte framgår av själva materialet eller om det är fråga om en känd offentlig person.</li>
      <li>Kommentarer som kränker könet, åldern, härkomsten, språket, religionen eller andra personliga egenskaper hos författaren eller personer som förekommer i materialet. Innehållet i en kommentar bör anknyta till materialet.</li>
    </ul>

    <p>Vi håller fast vid följande principer för att kommentarsdelen ska vara ändamålsenlig.</p>
    <ul class="list-bullets">
      <li>Kommentarerna bör inte innehålla spoilrar av fiktivt material, såsom böcker och filmer.</li>
      <li>Om du vill ställa frågor till den som tillhandahåller materialet eller observerar problem med tillgängligheten ska du i första hand använda de blanketter som är avsedda för ändamålen.</li>
    </ul>
    <p>Du kan vid behov redigera eller radera dina kommentarer.</p>
    <p>Dina kommentarer publiceras med ditt namn eller din signatur i alla Finnas söktjänster och webbibliotek där materialet finns till påseende. Alla kommentarer är offentliga. Du kan välja en pseudonym och ändra den under avsnittet <a href="<?=$this->url('myresearch-profile')?>">Mina kontouppgifter</a> i ditt konto.</p>
  </div>
</div>
<!-- END of: finna - content/help-comments-ratings_sv.phtml -->
