<?php
    if ($this->driver->isCollection()) {
        $linkText = $this->driver->tryMethod('getArchiveType') === 'collection' ? 'View Full Collection' : 'View Full Archive';
    } else {
        $linkText = 'View Full Record';
    }
?>
<h2><?=$this->escapeHtml($this->driver->getTitle())?></h2>
<a href="<?=$this->escapeHtmlAttr($this->recordLinker()->getUrl($this->driver))?>">
    <?=$this->transEsc($linkText)?>
</a>

<?=
  $this->record($this->driver)->renderTemplate(
      'core-fields.phtml',
      [
        'driver' => $this->driver,
        'defaults' => 'collection-record',
      ]
  );
?>
