<!-- START of: finna - RecordDriver/DefaultRecord/record-image-paginator.phtml -->
<?php
  if (!$images) {
    return;
  }
  $isList = ($type === 'list' || $type === 'list grid');
  $isBot = $this->userAgent()->isBot();
  if ($isBot && $type !== 'record') {
    return;
  }
?>
<?php if ($isBot): ?>
  <?php foreach ($this->recordImage($this->record($this->driver))->getImagesForBotUser($images) as $image): ?>
    <div>
      <?php if ($image['pdf']): ?>
        <a href="<?=$this->escapeHtmlAttr($image['url'])?>"><?=$this->escapeHtml($image['id']);?></a>
      <?php else: ?>
        <img src="<?=$this->escapeHtmlAttr($image['url'])?>">
      <?php endif;?>
    </div>
    <br>
  <?php
    endforeach;
    // Notice this return statement for bots.
    return;
  ?>
<?php endif; ?>

<?php
  $renderedImagesCount = count($images);
  $totalImagesCount = $this->driver->tryMethod('getTotalAmountOfImages') ?? $renderedImagesCount;
  $settings = [
    'recordId' => $this->driver->getUniqueId(),
    'recordType' => $this->driver->tryMethod('getRecordFormat'),
    'recordSource' => $this->driver->tryMethod('getSourceIdentifier'),
    'enableImageZoom' => $this->record($this->driver)->getImagePopupZoom(),
    'maxRows' => 3,
    'iconlabelClass' => 'format-' . $this->record($this->driver)->getFormatClass(end($formats)),
    'isList' => $type === 'list' || $type === 'list grid',
    'recordCovers' => 'recordcovers',
    'displayIcon' => $displayIcon,
    'triggerClick' => $this->imageClick ?? 'modal',
    'totalImagesCount' => $totalImagesCount,
  ];
  if ($this->driver->tryMethod('getModels')) {
    $modelSettings = $this->driver->tryMethod('getModelSettings', [], []);
    $settings['modelTranslations'] = $this->partial('Helpers/modeljs-translations.phtml');
    $settings['viewerDebug'] = $modelSettings['debug'] ?? false;
  }
  $inSearchContext = ($this->renderContext ?? false) === \Finna\RecordDriver\RenderContext::SEARCH;

  $imageIndexAttrs = [
    'class' => 'image-index',
  ];
  $leftButtonAttrs = [
    'class' => 'left-button',
    'type' => 'button',
    'title' => $this->translate('previous_images'),
  ];
  $rightButtonAttrs = [
    'class' => 'right-button',
    'type' => 'button',
    'title' => $this->translate('next_images'),
  ];
  if ($inSearchContext) {
    $imageIndexAttrs['class'] .= ' visible-md visible-lg';
    $leftButtonAttrs['class'] .= ' visible-md visible-lg';
    $rightButtonAttrs['class'] .= ' visible-md visible-lg';
  }
  $manifests = $this->driver->tryMethod('getIiifManifests');
  $iiifLogo = $this->imageSrc()->getSourceAddress('iiif_logo.min');
?>

<div class="recordcover-container">
  <button class="next-image left" type="button"><?=$this->icon('image-previous') ?><span class="visually-hidden"><?= $this->transEsc('previous_image') ?></span></button>
  <a class="image-popup-trigger init" draggable="false" href="<?=$this->escapeHtmlAttr($this->recordLinker($this->results ?? null)->getUrl($this->driver)) ?>" data-images="<?=htmlspecialchars(json_encode($images ?? []), ENT_QUOTES, 'UTF-8');?>" data-settings="<?=htmlspecialchars(json_encode($settings ?? []), ENT_QUOTES, 'UTF-8');?>" tabindex="-1">
    <div class="iconlabel format-<?=$this->record($this->driver)->getFormatClass(end($formats))?>"></div>
    <div class="paginator-info d-flex align-items-center">
      <span<?=$this->htmlAttributes($imageIndexAttrs)?>></span>
      <?php if ($inSearchContext): ?>
        <span class="visible-xs visible-sm"><?=$this->escapeHtml($totalImagesCount)?></span>
      <?php endif; ?>
      <?php if ($renderedImagesCount < $totalImagesCount && !$this->translationEmpty('showing_first_images_html')): ?>
        <?=$this->component('finna-toggletip', [
          'icon' => 'info',
          'contentHtml' => $this->translate('showing_first_images_html', ['%%start%%' => 1, '%%end%%' => $renderedImagesCount, '%%total%%' => $totalImagesCount]),
          'class' => 'partial-images',
        ]);?>
      <?php endif; ?>
    </div>
    <img src="<?=$this->imageSrc()->getDataPixel()?>" data-src="<?=$this->url('cover-unavailable')?>" class="recordcover<?= ($images[0]['pdf'] ?? false) ? ' pdf-cover' : ''?>" alt="<?=$this->transEsc('No Cover Image')?>">
  </a>
  <?php if ($manifests): ?>
    <button type="button"
            class="badge text-bg-light position-absolute bottom-0 end-0 icon-link iiif-menu-button-badge"
            data-bs-toggle="dropdown"
            aria-expanded="false">
        <img src="<?=$this->escapeHtmlAttr($iiifLogo)?>"
            alt="IIIF"
            class="bi">
    </button>
    <?=$this->component('finna-iiif-menu',
                        ['manifestUrls' => $manifests,
                        'uniqueID' => md5($settings['recordId'])]);?>
  <?php endif ?>
  <span class="hidden-trigger" hidden></span>
  <button class="next-image right" type="button"><?=$this->icon('image-next') ?><span class="visually-hidden"><?= $this->transEsc('next_image') ?></span></button>
</div>

<div class="recordcover-image-detail">
  <p class="image-description"></p>
</div>

<div class="recordcovers <?=$this->escapeHtmlAttr($type)?>">
  <button<?=$this->htmlAttributes($leftButtonAttrs)?>><?=$this->icon('image-previous') ?><span class="visually-hidden"><?= $this->transEsc('previous_images') ?></span></button>
  <div class="track-holder paginator-mask">
    <div class="finna-element-track"></div>
  </div>
  <button<?=$this->htmlAttributes($rightButtonAttrs)?>><?=$this->icon('image-next') ?><span class="visually-hidden"><?= $this->transEsc('next_images') ?></span></button>
</div>
<div class="recordcovers-more more-area">
  <button type="button" class="show-more-images"><?= $this->transEsc('more') ?> <?=$this->icon('image-more') ?></button>
  <button type="button" class="show-less-images"><?= $this->transEsc('less') ?> <?=$this->icon('image-less') ?></button>
</div>
<!-- END of: finna - RecordDriver/DefaultRecord/record-image-paginator.phtml -->
