<!-- START of: finna - search/list-compact.phtml -->
<?php
  if (!isset($this->indexStart)) {
    $this->indexStart = 0;
  }
  $showCheckboxes = $this->searchSettings($this->results->getParams())->checkboxesEnabled();
?>
<div class="<?=$this->escapeHtmlAttr(trim('record-list ' . ($this->resultsClass ?? '')))?>"<?=isset($this->resultsAttrs) ? ' ' . $this->resultsAttrs : ''?>>
  <?php $list = $this->sortList ? $this->sortList : $this->params->getSortList(); ?>  
  <?php if ($list['title']['selected'] ?? false): ?>
    <?=$this->render('search/sort-title-message.phtml')?>
  <?php endif; ?>
  <?php $i = $this->indexStart;
  foreach ($this->results->getResults() as $current):
    $recordNumber = $this->results->getStartRecord() + $i - $this->indexStart; ?>
    <div id="result<?=$i++ ?>" class="result condensed-list-view clearfix <?=$this->record($current)->getContainerJsClasses()?>">
      <?php if ($showCheckboxes): ?>
        <div class="record-checkbox">
          <?=$this->record($current)->getCheckbox('', 'search-cart-form')?>
        </div>
      <?php endif; ?>
      <span class="visually-hidden"><?=$this->transEsc('Search Result');?> <?=$recordNumber ?></span>
      <?=$this->record($current)->getSearchResult('condensed', $this->results)?>
    </div>
  <?php endforeach; ?>
</div>
<!-- END of: finna - search/list-condensed.phtml -->
