<?php
  $seriesKeys = $this->driver->getSeriesKeys();
  $currentSeriesKey = $this->seriesKey ?? $seriesKeys[0];
  $results = $this->driver->getSeriesResult($currentSeriesKey);
  $currentSeries = $this->driver->getSeriesFromSeriesKey($currentSeriesKey);
  $recordId = $this->driver->getUniqueId();
  $searchQuery = 'series_key_str_mv:"' . $currentSeriesKey . '"';
  $searchUrlEscaped = $this->url('search-results', options: ['query' => ['lookfor' => $searchQuery]]);
?>
<div class="record-tab-series-container">
  <div class="series-header">
    <?php if ($currentSeries): ?>
      <h2 id="series"><?=$this->escapeHtml($currentSeries)?></h2>
    <?php endif; ?>
    <div class="series-controls">
      <?=
        $this->translate(
            'showing_results_of_html',
            [
              '%%start%%' => 1,
              '%%end%%' => count($results),
              '%%total%%' => $this->localizedNumber($results->getTotal()),
            ]
        );
      ?>

      <?php if (count($seriesKeys) > 1): ?>
        <span class="series-dropdown-text"><?= $this->transEsc('Series')?>:</span>
        <div class="view-dropdown">
          <div class="dropdown">
            <a id="dropdown-toggle" type="button" class="dropdown-toggle series-dropdown-toggle" data-bs-toggle="dropdown" aria-expanded="false">
              <?=$this->escapeHtml($currentSeries)?>
              <?=$this->icon('dropdown-open') ?>
            </a>
            <ul class="dropdown-menu">
              <?php foreach ($seriesKeys as $key): ?>
                <li>
                  <a class="dropdown-item dropdown__link" href="#" data-id="<?=$this->escapeHtmlAttr($recordId)?>" data-source="<?=$this->escapeHtmlAttr($this->driver->getSourceIdentifier())?>" data-serieskey="<?=$this->escapeHtmlAttr($key)?>">
                    <?=$this->escapeHtml($this->driver->getSeriesFromSeriesKey($key))?>
                  </a>
                </li>
              <?php endforeach; ?>
            </ul>
          </div>
        </div>
      <?php endif; ?>
    </div>
  </div>
  <div class="series-tab-container js-series-tab-container container">
    <div class="list-scrollable">
      <button class="list-scrollable__scroll-prev-btn js-scroll-prev hidden" aria-label="<?=$this->transEscAttr('Scroll backward') ?>">
        <?=$this->icon('scrollable-prev')?>
      </button>
      <ul class="list-scrollable__list flex-row flex-nowrap overflow-x-auto">
        <?php foreach ($results as $source => $current): ?>
          <?php
            $formats = $current->getFormats();
            $seriesOrder = $current->getSeriesOrder($currentSeries);
            $orderForCurrentSeries = null;
            if ($seriesOrder) {
              $orderSeriesParts = explode(' ', $seriesOrder['orderKey']);
              $keySeriesParts = explode(' ', $currentSeriesKey);
              $orderForCurrentSeries = $orderSeriesParts[1] === $keySeriesParts[1];
            }
          ?>
          <li class="list-scrollable__list-item js-list-item <?= $recordId === $current->getUniqueId() ? 'active' : '' ?>">
            <?php if ($orderForCurrentSeries): ?>
              <span class="series"><?=$this->escapeHtml($seriesOrder['order'])?></span>
            <?php endif; ?>
            <a class="list-scrollable__item-container js-list-link" href="<?=$this->escapeHtmlAttr($this->recordLinker()->getUrl($current))?>">
              <div class="list-scrollable__image-container">
                <img class="list-scrollable__image" loading="lazy" src="<?=$this->recordImage($this->record($current))->getLargeImage()?>" alt="">
                <div class="list-scrollable__image iconlabel hidden format-<?=$this->record($this->driver)->getFormatClass(end($formats))?>"></div>
              </div>
              <div class="list-scrollable__title-container">
                <span class="list-scrollable__title"><?=$this->escapeHtml($current->getTitle())?></span>
              </div>
            </a>
          </li>
        <?php endforeach; ?>
        <?php if (count($results) < $results->getTotal()): ?>
          <li class="list-scrollable__list-item js-list-item show-more">
            <a class="list-scrollable__item-container js-list-link" href="<?=$searchUrlEscaped?>">
              <div class="list-scrollable__image-container">
                <div class="list-scrollable__image">
                  <?=$this->icon('view-list')?>
                  <?=$this->transEsc('find_more_ellipsis')?>
                </div>
              </div>
            </a>
          </li>
        <?php endif; ?>
      </ul>
      <button class="list-scrollable__scroll-next-btn js-scroll-next hidden" aria-label="<?=$this->transEscAttr('Scroll forward') ?>">
        <?=$this->icon('scrollable-next')?>
      </button>
    </div>
  </div>
  <?php $searchQuery = 'series_key_str_mv:"' . $currentSeriesKey . '"'; ?>
  <div class="series-search-link"><a href="<?=$searchUrlEscaped?>" class="btn btn-primary"><?= $this->transEsc('channel_search') ?> (<?=$results->getTotal()?>)</a></div>
</div>
<?php
  $script = <<<JS
      finna.scrollableList.initScrollableList(document.querySelector('.js-series-tab-container'));
      finna.series.init();
      JS;
?>
<?=$this->assetManager()->outputInlineScriptString($script);?>
