<?php // Do not add start and end tags
  if ($this->cookie()->get('hidePreProductionWarning')) {
    return;
  }
  $preproductionRedirect = $this->config()->get('config')->System->preProductionRedirect;
  $productionUrl = '';
  if ($preproductionRedirect) {
    $redirects = is_object($preproductionRedirect)
      ? $preproductionRedirect->toArray() : (array)$preproductionRedirect;
    foreach ($redirects as $redirect) {
      $parts = explode('###', $redirect);
      if (isset($parts[1])) {
        $productionUrl = preg_replace($parts[0], $parts[1], $this->serverUrl(true), -1, $count);
        if (!$count) {
          $productionUrl = '';
        } else {
          break;
        }
      }
    }
  }
  if (!$productionUrl) {
    return;
  }

  $script = <<<JS
      $('.js-pre-production-ok-button').on('click', function dismissWarning() {
        VuFind.cookie.set('hidePreProductionWarning', 1, { expires: 1/24 });
        $('.pre-production-warning').addClass('hidden');
      });
      JS;
?>

<div class="container-fluid pre-production-warning">
  <div class="pre-production-warning__text">
    <?=$this->translate('preproduction_warning_html', ['%%url%%' => $this->escapeHtmlAttr($productionUrl)])?>
  </div>
  <div class="nav navbar-nav nav-absolute pre-production-warning__button-container">
    <button class="btn btn-primary pre-production-warning__dismiss js-pre-production-ok-button" aria-label="<?=$this->transEscAttr('close')?>"><?=$this->transEsc('OK')?></button>
    <?=$this->assetManager()->outputInlineScriptString($script)?>
  </div>
</div>
