<?php $loginMethod = $this->auth()->getManager()->getILSLoginMethod(); ?>
<?php if ('email' === $loginMethod): ?>
  <div class="form-group">
    <label class="control-label" for="login_<?=$this->escapeHtmlAttr($topClass)?>_username"><?=$this->transEsc('Email')?>:</label>
    <input type="text" name="username" id="login_<?=$this->escapeHtmlAttr($topClass)?>_username" value="<?=$this->escapeHtmlAttr($this->request->get('username'))?>" class="form-control" required aria-describedby="<?=$this->escapeHtmlAttr($topClass)?>_username_desc">
    <p id="<?=$this->escapeHtmlAttr($topClass)?>_username_desc"><?=$this->transEsc('Required Field')?></p>
  </div>
<?php else: ?>
  <div class="form-group">
    <label class="control-label" for="login_<?=$this->escapeHtmlAttr($topClass)?>_username"><?=$this->transEsc('Username')?>:</label>
    <input type="text" name="username" id="login_<?=$this->escapeHtmlAttr($topClass)?>_username" value="<?=$this->escapeHtmlAttr($this->request->get('username'))?>" class="form-control" required aria-describedby="<?=$this->escapeHtmlAttr($topClass)?>_username_desc">
    <p id="<?=$this->escapeHtmlAttr($topClass)?>_username_desc"><?=$this->transEsc('Required Field')?></p>
  </div>

  <div class="form-group">
    <label class="control-label" for="login_<?=$this->escapeHtmlAttr($topClass)?>_password"><?=$this->transEsc('Password')?>:</label>
    <input type="password" name="password" id="login_<?=$this->escapeHtmlAttr($topClass)?>_password" class="form-control" required aria-describedby="<?=$this->escapeHtmlAttr($topClass)?>_password_desc">
    <p id="<?=$this->escapeHtmlAttr($topClass)?>_password_desc"><?=$this->transEsc('Required Field')?></p>
  </div>
<?php endif; ?>
