Subject: Finna: ilmoitus tietokannan <?=$source?> epäonnistuneista verkkomaksuista

Finnan kautta on maksettu <?=$errorCount?> kpl tietokannan <?=$source?> verkkomaksua, joiden rekisteröinti kirjastojärjestelmään on epäonnistunut. Maksut on veloitettu asiakkaiden tileiltä.

Epäonnistunut maksutapahtuma tulee kuitata maksetuksi Finnan hallintaliittymässä ennen kuin asiakas voi maksaa uusia verkkomaksuja.

https://hallinta.finna-pre.fi (>> Verkkomaksut)

Ohjeet:
https://www.kiwi.fi/display/Finna/Verkkomaksut
